/*
Signal Schedule
Area: Signal Schedule
File: pages/requests/approvals.js
Version: v5.16.1
Purpose: Render Approval Foundation preview with decision model and graceful data fallback.
*/
const $ = (selector) => document.querySelector(selector);
const safe = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
function statLabel(key){ return key.replace(/([A-Z])/g,' $1').replace(/^./, c => c.toUpperCase()); }
const fallback = {"version": "5.16.1", "summary": {"pending": 7, "approvedToday": 3, "deniedToday": 1, "escalations": 2}, "queues": [{"name": "Leave Requests", "route": "Employee \u2192 Supervisor \u2192 Scheduler", "permission": "Supervisor or higher", "pending": 3}, {"name": "Open Shift / VOT", "route": "Employee \u2192 Scheduler", "permission": "Scheduler", "pending": 2}, {"name": "Profile Changes", "route": "Employee \u2192 Admin Review", "permission": "Admin", "pending": 1}, {"name": "Benefit Adjustments", "route": "Admin-only decision", "permission": "Admin", "pending": 1}], "requests": [{"id": "REQ-1001", "employee": "Morgan Price", "type": "Vacation", "reason": "Family trip", "status": "Pending supervisor review", "currentStep": "Supervisor review", "hours": 12, "submitted": "2026-06-15 09:14", "coverage": "Day shift remains above minimum", "eligibility": "Eligible", "recommendation": "Approve if no later conflicts appear"}, {"id": "REQ-1002", "employee": "Avery Brooks", "type": "Sick Leave", "reason": "Illness", "status": "Pending scheduler impact", "currentStep": "Coverage impact", "hours": 8, "submitted": "2026-06-15 10:22", "coverage": "Creates one short coverage block", "eligibility": "Eligible", "recommendation": "Hold until replacement found"}, {"id": "REQ-1003", "employee": "Jordan Lee", "type": "VOT", "reason": "Extra hours", "status": "Pending award", "currentStep": "Scheduler decision", "hours": 4, "submitted": "2026-06-15 11:05", "coverage": "Fills open shift", "eligibility": "Eligible", "recommendation": "Award"}], "chains": [{"workflow": "Standard Leave", "steps": ["Submitted", "Supervisor Review", "Coverage Check", "Scheduler Final", "Posted"]}, {"workflow": "Sick Leave", "steps": ["Submitted", "Eligibility Check", "Supervisor Notice", "Ledger Pending", "Posted"]}, {"workflow": "VOT/Open Shift", "steps": ["Posted", "Volunteer", "Eligibility", "Award", "Schedule Update"]}], "policyChecks": ["User has permission to decide current step.", "Request type allows the selected reason.", "Partial-day hours follow agency increment rules unless admin override is used.", "Coverage impact is reviewed before final posting.", "Every decision creates an audit event."], "decisionModel": {"actions": ["approve", "deny", "return_for_info", "escalate"], "requiredFields": ["decision", "decisionBy", "decisionAt", "comment", "nextStatus"], "notes": "Preview-only in v5.9. Live write actions are reserved for backend-connected releases."}};
function render(data){
  $('[data-approval-stats]').innerHTML = Object.entries(data.summary || {}).map(([key,value]) => `<div class="approval-stat"><strong>${safe(value)}</strong><span>${statLabel(key)}</span></div>`).join('');
  $('[data-approval-queues]').innerHTML = (data.queues || []).map(queue => `<article class="queue-card"><h3>${safe(queue.name)}</h3><p>${safe(queue.route)}</p><p><strong>Authority:</strong> ${safe(queue.permission)}</p><span class="pending">${safe(queue.pending)} pending</span></article>`).join('');
  $('[data-approval-requests]').innerHTML = (data.requests || []).map(request => `<article class="request-card"><div><h3>${safe(request.type)}</h3><p><strong>${safe(request.employee)}</strong></p><p>${safe(request.reason)}</p><div class="request-meta"><span class="approval-badge">${safe(request.id)}</span><span class="approval-badge warning">${safe(request.status)}</span></div></div><div><p><strong>Step:</strong> ${safe(request.currentStep)}</p><p><strong>Hours:</strong> ${safe(request.hours)}</p><p><strong>Submitted:</strong> ${safe(request.submitted)}</p></div><div><p><strong>Coverage:</strong> ${safe(request.coverage)}</p><p><strong>Eligibility:</strong> ${safe(request.eligibility)}</p><p><strong>Recommendation:</strong> ${safe(request.recommendation)}</p></div></article>`).join('');
  $('[data-approval-chains]').innerHTML = (data.chains || []).map(chain => `<article class="chain-card"><h3>${safe(chain.workflow)}</h3><div class="chain-steps">${(chain.steps || []).map(step => `<span>${safe(step)}</span>`).join('')}</div></article>`).join('');
  $('[data-policy-checks]').innerHTML = (data.policyChecks || []).map(note => `<li>${safe(note)}</li>`).join('');
  const decision = data.decisionModel || {};
  const mount = $('[data-decision-model]');
  if (mount) mount.innerHTML = `<article class="chain-card"><h3>Actions</h3><div class="chain-steps">${(decision.actions || []).map(action => `<span>${safe(action)}</span>`).join('')}</div></article><article class="chain-card"><h3>Required Fields</h3><div class="chain-steps">${(decision.requiredFields || []).map(field => `<span>${safe(field)}</span>`).join('')}</div></article><article class="chain-card"><h3>Write Status</h3><p>${safe(decision.notes || 'Preview-only until backend writes are enabled.')}</p></article>`;
}
async function init(){
  const loader = window.SignalScheduleData;
  const data = loader?.loadJsonOrFallback ? await loader.loadJsonOrFallback('/data/approval-foundation-preview.json', fallback) : fallback;
  render(data || fallback);
}
init();
